---
title: "Land Use and Water Quality"
author: "Dr. Matthew Ross"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  #bookdown::pdf_book: default
---


# Land Use and Water Quality (WR418)

This working repository hosts all lecture material, code, assignments, and the syllabus for Land Use and Water Quality (WR418) taught at Colorado State University.

The long-term vision for this project is to work towards an open access book
similar to [R for Data Science](https://r4ds.had.co.nz/), which can be used to teach
college students about the interaction of human land-use and downstream water quality
change.

## Goals

The broadest goals of the book/course are for students to develop both an 
intuitive and quantitative understanding of:

- How human decisions about land-use alters how water moves through the landscape,
 the materials it picks up, and, what we can and can't do to improve degraded water quality.
 
- The chemical reactions and processes that govern the connection between land-use
and downstream water quality, over short and long time-scales.
 
- The history of human impacts to water quality from water quality impacts in 
ancient rome to modern pharmaceuticals entering our lakes and rivers.

- The status of water quality in lakes and rivers across the globe and how it relates
to legislation, developoment, and environmental change broadly.

## Approach

To reach these educational goals we will use a variety of approaches focused on 
engaging students directly with primarily literature on water quality, discussing
current events related to land-use and water quality, quantitative analyses of 
land-use and water quality change over time, and a focused final project. 

