# Chemical weathering and acididity

The ultimate source of many nutrients key to life come from the 
chemical weathering of bedrock, or the dissolving of solid parent material into
its component elements of base cations, anions, metals, and other trace elements.
Chemical weathering happens when water, filled with organic, carbonic, and
other acids, reaches bedrock, which it slowly dissolves. Humans have profoundly 
altered weathering rates across the world, by increasing the amount of acidity
in rain, streamwater, and from mining. Increasing chemical weathering rates
mobilizes more cations and anions along with other metals and trace elements, 
increasing their concentrations in freshwaters. 

As with previous lessons, the folks at Crash Course have built a series of videos
that provide an excellent review of the key chemistry ideas that govern chemical
weathering rates and how humans have altered these rates. 

## Acid rain

One of the most profound and widespread impacts people have had on chemical 
weathering rates is by increasing the acidity of rain. Essentially, combustion of
coal and other fossil fuels, releases $NO_x$ and $SO_x$ compounds, which interact
with water vapor to form the strong acids: nitric and sulfuric acid. 
Higher acidity from these compounds leads to higher weathering rates 
(or in the case of the video, higher statue-melting rates). 

<iframe width="560" height="315" src="https://www.youtube.com/embed/ANi709MYnWg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### pH review

One critical idea when working in acid-base chemistry is the idea of a pH scale
(and it's inverse the pOH scale). The video below explains this idea quite clearly.

<iframe width="560" height="315" src="https://www.youtube.com/embed/LS67vS10O5Y" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


## Buffers

One way to lessen the impact of adding a strong acid or base to a solution is to 
buffer the system with weak acid and bases. The nuts and bolts of buffered 
solutions is explained in the below video. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/8Fdt5WnYn1k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## The carbonate equilibrium buffer

In natural waters the most important buffer is the carbonate equilibrium system
whereby $CO_2$ dissolves into solution forming both $HCO_3^-$ and $H_2CO_3$. 
Excess $HCO_3^-$ in natural waters acts as a natural buffer, limiting the
impact of additonal acids being added to the system. Other buffers exisit in
natural systems and the sum of their ability to absorb incoming acids is called:
**Alkalinity**. 

This [paper](http://www.chem1.com/acad/pdf/c3carb.pdf) by Stephen Lower goes into 
much more detail about the carbonate equilibrium system, alkalinity, and natural 
waters. You should review this in addition to watching the above videos. 

## Acid-mine drainage

Acid-mine drainage is a human-induced change to natural waters 
that can completely override any alkalinity in the system
and dramatically reduce the pH to ~ 1 or 2. The primary culprit contributing all
this extra acidity is pyrite ($FeS_2$). When mining operations unearth bedrock
to access gold, coal, copper, or other resources, this bedrock is often 
enriched in pyrite or other sulfur bearing compounds. When these compounds 
are exposed to air and water the sulfur dissolves and oxidizes forming $H_2SO_4$
a strong acid. Because mining operations frequently concentrate the overburden
(the excess rock generated by mining), there is often large volumes of pyrite
in a relatively small areas. All this excess acidity, increases weathering
rates, and dissolving a suite of metals that are toxic to people and biota, in 
addition to the direct problems from low pH. Acid-mine drainage is a problem
for both new and old mines and it can be a problem that lasts for decades or 
centuries. This [paper](https://www.sciencedirect.com/science/article/pii/S0048969705008089) provides
an excellent overview of how Acid-Mine Drainage problems occur and some approaches
people have used to address them.


## Additional human impacts to weathering rates

Lowering the acidity of rain and streams may be the most important
ways in which humans have altered weathering rates, releasing metals and other 
trace elements into freshwaters. However, weathering rates are not only controlled
by acidity. Chemical weathering rates increase with a number of other variables
including: 

  - Increasing temperatures (because of reaction kinetics)

  - Increasing reactive surface area of bedrock (more reaction sites)
  
  - Increasing water flux (more constantly refreshed reaction interface)
  
Humans are actively increasing all of these controls on weathering through climate
change (increased temperature, increased rainfall in some areas), increasing surface 
area of bedrock (construction, earth-moving, surface mining), and increasing 
water flux through ecosystems (agricultural irrigation, lawn irrigiation). 
Increasing weathering rates can [increase the salinity of freshwaters](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2017GB005798),
[increase the alkalinity in rivers](https://aslopubs.onlinelibrary.wiley.com/doi/full/10.1002/lol2.10069),
and [increase trace element concentration in rivers](ftp://ft.dphe.state.co.us/wqc/wqcc/32_36TriennialReviewRMH_2013/ResponsivePrehearingStatement/PuebloCounty5.pdf)

The net result of all these alterations to weathering processes and rates, plus a
variety of other human impacts on freshwaters are creating novel [chemical cocktails](https://royalsocietypublishing.org/doi/full/10.1098/rstb.2018.0017) in 
freshwaters throughout the world. The impacts of novel combinations of elements
on aquatic life and people are poorly understood. 


