---
title: "History of Water Quality Change"
author: "Matthew Ross"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  ioslides_presentation:
    incremental: true
    widescreen: true
    smaller: true
    transition: 0.01
editor_options: 
  chunk_output_type: console
---

<style>
slides > slide {
  overflow-x: auto !important;
  overflow-y: auto !important;
}
</style>

# History of Water Quality Change (Week 2)

## Housekeeping
- Email, and canvas communication norms
- Questions from last week?
- HW reminder

## Goals for today

- Start to build a timeline of human impacts on water
- Review approaches to finding, reading, and understanding primary literature

## Timeline of WQ Change

- In groups of 3 or 4 draw a timeline of any and all important moments, events,
ideas, regulations, etc... in the history of Water Quality change. 

- This can include things like: First evidence of cultural eutrophication, 
the Great Stink of London, Cholera identified as waterborne illness etc...

- Do your best to guess when these things happened, but it's okay to be wrong, we 
are going to fill this out as a class throughout the semester. 

## How would we systematically fill this out?

- Primary research literature is an important way to learn about the most 
current and well-supported ideas in a field.
- Reading primary literature can be difficult because of technical language,
confusing figures, and, unfortunately, bad-writing
- [Google Scholar](https://scholar.google.com/) 



