---
title: "HW3"
author: "Matthew Ross"
date: "2/15/2019"
header-includes: 
      - \usepackage{soulutf8}
      - \usepackage{gensymb}
output:
  pdf_document: default
  html_document: default
---

In this assignment you will be reviewing key Redox and nutrient ideas from class
The goal of this is to get you thinking about how chemistry controls many aspects
of water quality and how we can use that knowledge to improve water quality.

For all analytical responses show your work, this can be hand-written (your handwriting should be clear), typed up, or if you want to code it up in Rmarkdown and turn in a knitted html, I'd love that! 


1. What are some at least 3 key nutrients for life? Name one nutrient cycle that people
have radically altered. 

2. Redox reactions (reduction-oxidation reactions) are the reactions that power
much of life's functions. In a redox reaction what is being exchanged between 
elements and molecules that generates energy? 

3. What are two redox dependent reactions that can control nutrient concentrations
in freshwaters? Why are these reactions redox dependent? 


4. Oxidation number is an important concept for tracking where electrons are in 
a chemical reaction. What is the oxidation number for each element in the following
chemical equations? You should give just the oxidation number per element for example
for $Fe_2O_3$ the answer would be `O=-2, Fe = +3`. 

  + Acetate - $CH_3COO^-$
  + Sulfate - $SO_4^{2-}$
  + Hyrdrogen ion - $H^+$
  + Carbon Dioxide - $CO_2$
  + Hydrogen Sulfide - $H_2S$
  + Water - $H_2O$
  
5. Acetate can be used as an energy source for microbes in an oxic environment
with the equation:
  
    $CH_3COOH + 2O_2 -> 2CO_2 + H_2O$
    
    where acetate is oxidized by $O_2$ as the final electron acceptor (Remember
    oxidation is loss of electrons, reduction is gain of electrons). For this reaction,
    we can calculate the total Gibbs free energy relased using the equation: 
    
    $G^\degree = {\sum}\Delta G_{products} - {\sum}\Delta G_{reactants}$
    
    The standard gibbs free energy ($\Delta G_f^\degree$) for each component in the reaction is: 
    
     $CH_3COO^-$ = - 396.46 kJ/mol
     
     $O_2$ = 0 kJ/mol
     
     $CO_2$ = -385.98 kJ/mol
     
     $H_2O$ = -237.18 kJ/mol
    
    What is the G$^\degree$ for the entire reaction?
    (Remember to multiply $\Delta G$ values by the # of moles of each reactant and product)

6. What is the difference in standard free energy yields for these three reactions?

    $CH_3COOH + 2O_2 -> 2CO_2 + H_2O$
    
    $CH_3COOH + 2SO_4^{2-} + 2H^+ -> 2CO_2 + H_2S + 2 H_2O$
    
    $CH_3COOH + 2NO_3^- + 2H^+ -> 2CO_2 + N_2 + 4H_2O$
    
    Additional standard gibbs values you will need
    
      $SO_4^{2-}$ = -744.53 kJ/mol
      
      $H^+$ = 0 kJ/mol
      
      $H_2S$ = -27.83 kJ/mol
      
      $NO_3^-$ = -108.74 kJ/mol
      
      $N_2$ = 0 kJ/mol
  

7. Rank the final electron acceptors from the above equations in order of most gibbs free energy yield to least (use oxidation numbers to figure out which reactant loses and receives electrons)?

    